### ISSUE TITLE
Add ability to set color for highlighting selection.

### ISSUE THREAD

**Issue by billionaire** [SublimeText/WordHighlight#62]
Hello.
Thank you for your package. It very useful and convenient.
For even greater visual ease, it would be cool to add ability to set color in user-settings for highlighting selection(s).
This speeds up visual search of information.
For example, screenshot of Notepad++ and Sublime Text 3.
Thank you.
Sincerely.
![notepad](https://cloud.githubusercontent.com/assets/6255854/8267395/ef295b5c-1768-11e5-808f-fa3822b369c0.png)
![sublime_text_3](https://cloud.githubusercontent.com/assets/6255854/8267398/f2f8f328-1768-11e5-88cd-ff7f85415fe8.png)

**Comment by billionaire** [comment]
https://github.com/vcharnahrebel/style-token/blob/master/StyleToken.py
This is sample code for highlighting selected text fragment. Maybe it's not perfect, but anything is better than nothing.

**Comment by adzenith** [comment]
If you read the readme, you'll see that there's a way to customize the color. StyleToken does look easier; if you'd like to integrate something like that into WordHighlight feel free to send a pull request!
