### ISSUE TITLE
can you add a background color setting option

### ISSUE THREAD

**Issue by ilovezy** [SublimeText/WordHighlight#63]
I think the sometimes the color of comments sometime are to dark to see,
![qq 20150728212751](https://cloud.githubusercontent.com/assets/8774988/8932384/68c56310-356f-11e5-936b-a02d4c574ca5.png)

I hope you can add a setting options which maybe like this

"wordhighlight_background": "orange",
"wordhighlight_font_color": "white"

that will be great help for me 
since this is the only plugin I can find on sublime, please if it's not too hard

**Comment by adzenith** [comment]
The way Sublime Text works, we can't specify a color directly. You have to use a color scope name from your color scheme file. Check out the `color_scope_name` option in the readme.

**Comment by ilovezy** [comment]
I see, but how can i modify my color scheme file,
it look like a zip file
![qq 20150728231105](https://cloud.githubusercontent.com/assets/8774988/8935160/dbcadd28-357d-11e5-8498-853a1a2f47d4.jpg)

**Comment by adzenith** [comment]
It is indeed a zip file! Easiest is using "Edit Package Resource" from https://github.com/skuroda/PackageResourceViewer.

You can also just pick a different color from the unedited color scheme file.

**Comment by ilovezy** [comment]
ouch! thanks a lot
