### ISSUE TITLE
Can you add highlighting on scroll bar just like gutter bar

### ISSUE THREAD

**Issue by Satcheel** [SublimeText/WordHighlight#79]
I was using vs-code and found this variable instances highlighting very useful. I tried its alternative for sublime and this is the best I found. But I felt highlighting in scroll bar very helpful as you know where your cursor is and where you instances are. I feel that this extension would be complete if  it included that feature also. Anyway thanks for such good extension

**Comment by adzenith** [comment]
Sadly I don't believe this is possible in Sublime Text. I can only add highlights in the document, and it automatically adds highlights in the minimap.
