### ISSUE TITLE
Error trying to parse settings

### ISSUE THREAD

**Issue by jonassvedas** [SublimeText/WordHighlight#82]
When I start Sublime with this package installed this I get this error message.

Error trying to parse settings: Expected value in Packages/User/Word Highlight.sublime-settings:1:1

I simply click on and proceed. Nothing seems to be affected, but still.

![image](https://user-images.githubusercontent.com/7907366/51329522-97ad8680-1a6d-11e9-9b91-16efc373e406.png)

**Comment by deathaxe** [comment]
This indicates a malformed settings file, with invalid json content.
